export const STATUS_RELEASED = 'RELEASED';
export const STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const STATUS_TO_RELEASE = 'TO_RELEASE';

export const PROJECT_LIST = [
  {
    name: 'SpaceBudz',
    avatar: 'assets/img/avatar/SpaceBudz.jpg',
    banner: 'assets/img/banner/SpaceBudz.jpeg',
    twitter: 'spacebudzNFT',
    facebook: null,
    instagram: null,
    discord: 'https://discord.com/invite/ePJZBVwQNq',
    telegram: 'https://t.me/spacebudz',
    youtube: null,
    webpage: 'https://spacebudz.io/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_RELEASED,
  },
  {
    name: 'CardanoBits',
    avatar: 'assets/img/avatar/CardanoBits.jpg',
    banner: 'assets/img/banner/CardanoBits.png',
    twitter: 'CardanoBits',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: 'https://t.me/CardanoBitsOfficial',
    youtube: null,
    webpage: 'https://cardanobits.art/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'Professor Cardano',
    avatar: 'assets/img/avatar/Professor Cardano.jpg',
    banner: 'assets/img/banner/Professor Cardano.jpeg',
    twitter: 'ProfesCardano',
    facebook: 'https://www.facebook.com/Professor-Cardano-109421374554689',
    instagram: 'https://www.instagram.com/professor_cardano/',
    discord: null,
    telegram: null,
    youtube: null,
    webpage: 'https://www.professorcardano.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_IN_PROGRESS,
  },
  {
    name: 'Crypto Knitties',
    avatar: 'assets/img/avatar/Crypto Knitties.jpg',
    banner: 'assets/img/banner/Crypto Knitties.jpeg',
    twitter: 'cryptoknitties',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    webpage: 'https://adaknitties.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'Cardano Kidz',
    avatar: 'assets/img/avatar/Cardano Kidz.jpg',
    banner: 'assets/img/banner/Cardano Kidz.jpeg',
    twitter: 'cardanokidz',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    webpage: 'https://www.cardanokidz.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_IN_PROGRESS,
  },
  {
    name: 'ADA Dolls',
    avatar: 'assets/img/avatar/ADA Dolls.jpg',
    banner: 'assets/img/banner/ADA Dolls.jpeg',
    twitter: 'AdaDolls',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    webpage: 'https://adadolls.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'MAD in Art',
    avatar: 'assets/img/avatar/MAD in Art.jpg',
    banner: 'assets/img/banner/MAD in Art.jpeg',
    twitter: 'MADinArt3',
    facebook: 'https://www.facebook.com/MadinArtio-111659197638577/',
    instagram: 'https://www.instagram.com/mad.nft/',
    discord: null,
    telegram: null,
    youtube: 'https://www.youtube.com/channel/UCDxsNWLuJHH1T9KYHErvp4w',
    webpage: 'https://madinart.io/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_RELEASED,
  },
  {
    name: 'StigmaNFT',
    avatar: 'assets/img/avatar/StigmaNFT.jpg',
    banner: 'assets/img/banner/StigmaNFT.jpeg',
    twitter: 'StigmaNFT',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    webpage: null,
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'CryptoMayor',
    avatar: 'assets/img/avatar/CryptoMayor.jpg',
    banner: 'https://via.placeholder.com/1500x500/?text=CryptoMayor',
    twitter: 'cryptomayorNFT',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    webpage: 'https://cryptomayor.io/',
    mintedToken: '',
    dateRelease: '',
    policyID: '5e889bcb83b884bb6d768cfc483845cd6ccee79c2b5a4a15dae7ff47',
    status: STATUS_IN_PROGRESS,
  },
  {
    name: 'Cardano Kings & Queens',
    avatar: 'assets/img/avatar/Cardano Kings & Queens.jpg',
    banner: 'assets/img/banner/Cardano Kings & Queens.jpeg',
    twitter: 'ADAKingsQueens',
    facebook: 'https://www.facebook.com/ADAKingsQueens',
    instagram: 'https://instagram.com/wix/',
    discord: null,
    telegram: null,
    youtube: null,
    webpage: 'https://www.cardanokingsandqueens.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: '5e889bcb83b884bb6d768cfc483845cd6ccee79c2b5a4a15dae7ff47',
    status: STATUS_IN_PROGRESS,
  },
  {
    name: '2140 by withspaces',
    avatar: 'assets/img/avatar/2140 by withspaces.jpg',
    banner: 'assets/img/banner/2140 by withspaces.jpeg',
    twitter: '2140withspaces',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    webpage: 'http://withspaces.online/nfts/ch1/rodr160mugs/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'Crypties',
    avatar: 'assets/img/avatar/Crypties.jpg',
    banner: 'assets/img/banner/Crypties.jpeg',
    twitter: 'cryptiesnft',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    webpage: 'https://crypties.co/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  }
];

