export const STATUS_RELEASED = 'RELEASED';
export const STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const STATUS_TO_RELEASE = 'TO_RELEASE';

export const SPACEBUDZ_METADATA = {
  d5e6bf0500378d4f0da4e8dde6becec7621cd8cbf5cbb9b87013d4cc: {
    SpaceBud1919: {
      arweaveId: 'KTiDTKAr2zKcHYsACkvi3SB-OKyUR358QPvQYFVZY7w',
      image: 'ipfs://QmSRKfc5RNpv3dEib2h9ZAh3jMCrWrJu7p1g8HKCBu1MaS',
      name: 'SpaceBud #1919',
      traits: [
        'Chestplate',
        'Belt',
        'VR'
      ],
      type: 'Alien'
    }
  }
};

export const FINGERMONSTERS_METADATA = {
  c48399365969a5b3e08640d41bdd6581ecc814ff6cd5bb081556ffb1: {
    Wave1Aqua000: {
      id: 0,
      image: 'ipfs://ipfs/QmVpmdPsCdgbq5CDpCsJ7pmxNk1fnbkWSDmgRhDqCh6J9b',
      name: 'Finger Monsters Aqua [000]'
    },
  },
  copyright: 'Copyright Finger Monsters 2021; all rights reserved',
  publisher: [
    'cnft.io',
    'www.fingermonsters.com'
  ],
  version: 1
};

export const FINGERMONSTERS_RARITY = [
  { type: 'Flame', number: 150, rarity: 15 },
  { type: 'Spot', number: 150, rarity: 15 },
  { type: 'Tenti', number: 150, rarity: 15 },
  { type: 'Buzz Vegas', number: 125, rarity: 12.5 },
  { type: 'Drool', number: 100, rarity: 10 },
  { type: 'Bogey', number: 50, rarity: 5 },
  { type: 'Slick', number: 50, rarity: 5 },
  { type: 'Splodge', number: 50, rarity: 5 },
  { type: 'Aqua', number: 50, rarity: 5 },
  { type: 'Eyes', number: 25, rarity: 2.5 },
  { type: 'Tongue', number: 25, rarity: 2.5 },
  { type: 'Claws', number: 20, rarity: 2 },
  { type: 'Scales', number: 20, rarity: 2 },
  { type: 'Boggle', number: 10, rarity: 1 },
  { type: 'Spike', number: 5, rarity: 0.5 },
  { type: 'Wings', number: 5, rarity: 0.5 },
  { type: 'Red', number: 5, rarity: 0.5 },
  { type: 'Croco', number: 2, rarity: 0.2 },
  { type: 'Glob', number: 2, rarity: 0.2 },
  { type: 'Fin', number: 1, rarity: 0.1 },
  { type: 'Golden1', number: 1, rarity: 0.1 },
  { type: 'Golden2', number: 1, rarity: 0.1 },
  { type: 'Golden3', number: 1, rarity: 0.1 },
  { type: 'Golden4', number: 1, rarity: 0.1 },
  { type: 'Golden5', number: 1, rarity: 0.1 },
];

export const SPACEBUDZ_PROJECT = {
  hasDetailView: true,
  detailViewUrl: ['/', 'SpaceBudz'],
  name: 'SpaceBudz',
  avatar: 'assets/img/avatar/SpaceBudz.jpg',
  banner: 'assets/img/banner/SpaceBudz.jpeg',
  twitter: 'spacebudzNFT',
  facebook: null,
  instagram: null,
  discord: 'https://discord.com/invite/ePJZBVwQNq',
  telegram: 'https://t.me/spacebudz',
  youtube: null,
  reddit: null,
  webpage: 'https://spacebudz.io/',
  tokenInfo: '10.000 tokens minted and released',
  priceInfo: 'Starting at 10 ADA each, increasing the price every 1000 tokens (10, 20, ..., 90, 100)',
  dateRelease: '',
  metadata: SPACEBUDZ_METADATA,
  policyID: ['d5e6bf0500378d4f0da4e8dde6becec7621cd8cbf5cbb9b87013d4cc'],
  status: STATUS_RELEASED,
  lastUpdated: '07 April 2021',
};

export const FINGERMONSTERS_PROJECT = {
  hasDetailView: true,
  detailViewUrl: ['/', 'FingerMonsters'],
  name: 'Finger monsters',
  avatar: 'assets/img/avatar/Finger monsters.jpg',
  banner: 'assets/img/banner/Finger monsters.jpeg',
  twitter: 'CNFT_IO',
  facebook: null,
  instagram: null,
  discord: null,
  telegram: null,
  youtube: null,
  reddit: null,
  webpage: 'https://www.fingermonsters.com/',
  tokenInfo: '1.000 tokens minted and released @ Wave1',
  priceInfo: '50 ADA each @ Wave1',
  dateRelease: '',
  metadata: FINGERMONSTERS_METADATA,
  rarity: FINGERMONSTERS_RARITY,
  policyID: ['c48399365969a5b3e08640d41bdd6581ecc814ff6cd5bb081556ffb1'],
  status: STATUS_RELEASED,
  lastUpdated: '08 April 2021',
};

export const PROJECT_LIST = [
  SPACEBUDZ_PROJECT,
  FINGERMONSTERS_PROJECT,
  {
    name: 'CardanoBits',
    avatar: 'assets/img/avatar/CardanoBits.jpg',
    banner: 'assets/img/banner/CardanoBits.png',
    twitter: 'CardanoBits',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: 'https://t.me/CardanoBitsOfficial',
    youtube: null,
    reddit: null,
    webpage: 'https://cardanobits.art/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'Professor Cardano',
    avatar: 'assets/img/avatar/Professor Cardano.jpg',
    banner: 'assets/img/banner/Professor Cardano.jpeg',
    twitter: 'ProfesCardano',
    facebook: 'https://www.facebook.com/Professor-Cardano-109421374554689',
    instagram: 'https://www.instagram.com/professor_cardano/',
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'https://www.professorcardano.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_IN_PROGRESS,
  },
  {
    name: 'Crypto Knitties',
    avatar: 'assets/img/avatar/Crypto Knitties.jpg',
    banner: 'assets/img/banner/Crypto Knitties.jpeg',
    twitter: 'cryptoknitties',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'https://adaknitties.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'Cardano Kidz',
    avatar: 'assets/img/avatar/Cardano Kidz.jpg',
    banner: 'assets/img/banner/Cardano Kidz.jpeg',
    twitter: 'cardanokidz',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'https://www.cardanokidz.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_IN_PROGRESS,
  },
  {
    name: 'ADA Dolls',
    avatar: 'assets/img/avatar/ADA Dolls.jpg',
    banner: 'assets/img/banner/ADA Dolls.jpeg',
    twitter: 'AdaDolls',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'https://adadolls.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'MAD in Art',
    avatar: 'assets/img/avatar/MAD in Art.jpg',
    banner: 'assets/img/banner/MAD in Art.jpeg',
    twitter: 'MADinArt3',
    facebook: 'https://www.facebook.com/MadinArtio-111659197638577/',
    instagram: 'https://www.instagram.com/mad.nft/',
    discord: 'https://discord.com/invite/wbBVZrCH',
    telegram: null,
    youtube: 'https://www.youtube.com/channel/UCDxsNWLuJHH1T9KYHErvp4w',
    reddit: null,
    webpage: 'https://madinart.io/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_RELEASED,
  },
  {
    name: 'StigmaNFT',
    avatar: 'assets/img/avatar/StigmaNFT.jpg',
    banner: 'assets/img/banner/StigmaNFT.jpeg',
    twitter: 'StigmaNFT',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'https://stigma.cards/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'CryptoMayor',
    avatar: 'assets/img/avatar/CryptoMayor.jpg',
    banner: 'https://via.placeholder.com/1500x500/?text=CryptoMayor',
    twitter: 'cryptomayorNFT',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'https://cryptomayor.io/',
    mintedToken: '',
    dateRelease: '',
    policyID: '5e889bcb83b884bb6d768cfc483845cd6ccee79c2b5a4a15dae7ff47',
    status: STATUS_IN_PROGRESS,
  },
  {
    name: 'Cardano Kings & Queens',
    avatar: 'assets/img/avatar/Cardano Kings & Queens.jpg',
    banner: 'assets/img/banner/Cardano Kings & Queens.jpeg',
    twitter: 'ADAKingsQueens',
    facebook: 'https://www.facebook.com/ADAKingsQueens',
    instagram: 'https://instagram.com/wix/',
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'https://www.cardanokingsandqueens.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: '5e889bcb83b884bb6d768cfc483845cd6ccee79c2b5a4a15dae7ff47',
    status: STATUS_TO_RELEASE,
  },
  {
    name: '2140 by withspaces',
    avatar: 'assets/img/avatar/2140 by withspaces.jpg',
    banner: 'assets/img/banner/2140 by withspaces.jpeg',
    twitter: '2140withspaces',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'http://withspaces.online/nfts/ch1/rodr160mugs/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'Crypties',
    avatar: 'assets/img/avatar/Crypties.jpg',
    banner: 'assets/img/banner/Crypties.jpeg',
    twitter: 'cryptiesnft',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    reddit: null,
    webpage: 'https://crypties.co/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'Cardano Comics',
    avatar: 'assets/img/avatar/Cardano Comics.jpg',
    banner: 'assets/img/banner/Cardano Comics.jpeg',
    twitter: 'CardanoComics',
    facebook: null,
    instagram: null,
    discord: null,
    telegram: null,
    youtube: null,
    reddit: 'https://www.reddit.com/r/CardanoComics/',
    webpage: 'https://www.cardanocomics.io/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
  {
    name: 'Cardano Gods',
    avatar: 'assets/img/avatar/Cardano Gods.jpg',
    banner: 'assets/img/banner/Cardano Gods.jpeg',
    twitter: 'CardanoGods',
    facebook: null,
    instagram: 'https://www.instagram.com/cardanogods/',
    discord: 'https://discord.gg/xmVWPc3V',
    telegram: null,
    youtube: null,
    reddit: 'https://www.reddit.com/r/CardanoGods/',
    webpage: 'https://www.cardanogods.com/',
    mintedToken: '',
    dateRelease: '',
    policyID: null,
    status: STATUS_TO_RELEASE,
  },
];

